import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  // Admin Modules

  {
    path: 'landing',
    title: 'Home',
    moduleName: 'landing',
    iconType: 'material-icons-two-tone',
    icon: 'home',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: 'badge bg-blue sidebar-badge float-right',
    submenu: [],
    outsideLink: false
  },

  {
    path: '',
    title: 'My Work',
    moduleName: 'dashboard',
    iconType: 'material-icons-two-tone',
    icon: 'work',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    outsideLink: false,
    submenu: [
      {
        path: 'https://bpprocessing.com/#/',
        title: 'BP Processing',
        moduleName: '',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
        outsideLink: true,
      },
      {
        path: '/petsocial/home',
        title: 'Pet Social (open source)',
        moduleName: '',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
        outsideLink: false,
      },
    ],
  },
  {
    path: '',
    title: 'Links',
    moduleName: '',
    iconType: 'material-icons-two-tone',
    icon: 'insert_link',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    outsideLink: false,
    submenu: [
      {
        path: 'https://www.linkedin.com/in/brandon-cunningham-a87559138/',
        title: 'LinkedIn',
        moduleName: '',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
        outsideLink: true,
      },
      {
        path: 'https://github.com/',
        title: 'Git hub',
        moduleName: '',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
        outsideLink: true,
      },
      {
        path: 'https://www.upwork.com/freelancers/~01aa23d52b5a8c98ca',
        title: 'Old Upwork',
        moduleName: '',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
        outsideLink: true,
      },
      {
        path: '/admin/teachers/about-teacher',
        title: 'Download Resume (PDF)',
        moduleName: '',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
        outsideLink: true,
      },
    ],
  },


];
